language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - pip install tox

env:
  - TOX_ENV=latest,
  - TOX_ENV=django.1.8.lts,
  - TOX_ENV=django.1.7

script:
  - tox -e $TOX_ENV -- tests_app
