language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - TOX_ENV=django.1.11
  - TOX_ENV=django.2.0

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV -- tests_app
